sprint 13 - Add controllers
VladimirKomov/java-shareit pull request #1
Opened 2022-12-30 18:03 UTC by VladimirKomov

2022-12-30 19:12 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +
лишние пустые строки

2022-12-30 19:13 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
Контроллер для Item уже добавлен. TODO уже не релевантно

2022-12-30 19:17 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        log.info("Create {}", userDto.toString());
У тебя есть обработчик исключений в проекте. Попробуй добавить туда обработку исключений, когда передаются неверные данные в контроллер
В таком случае ответ выглядит так
{
	"error": "400 BAD_REQUEST",
	"description": "Validation failed for argument [0] in public ru.practicum.shareit.user.dto.UserDto ru.practicum.shareit.user.UserController.addUser(ru.practicum.shareit.user.dto.UserDto): [Field error in object 'userDto' on field 'email': rejected value [email3email.com]; codes [Email.userDto.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@68add844,.*]; default message [must be a well-formed email address]] "
}
И внутри присутствует стек трейс, которые не нужен клиенту приложения

2022-12-30 19:18 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@PathVariable long userId, @RequestBody UserDto userDto) {
К сожалению на patch не работает проверка email пользователя
Такой запрос проходит
{
	"name":"nameItem",
	"email":"wrong_emailmail.com",
  "login":"login22",
	"birthday":"2012-04-23T18:25:43.511Z"
}

2022-12-30 19:20 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDtoResponse getItemById(@PathVariable long itemId) {
Похоже нужно добавить проверку входных параметров и ругаться соответствующе, если входные параметры не верны
{
	"error": "500 INTERNAL_SERVER_ERROR",
	"description": "Failed to convert value of type 'java.lang.String' to required type 'long'; nested exception is java.lang.NumberFormatException: For input string: \"фф\""
}

2022-12-30 19:21 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Замечаний почти нет

2022-12-30 19:26 UTC, VladimirKomov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +
готово

2022-12-30 19:29 UTC, VladimirKomov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
готово

2022-12-30 19:50 UTC, VladimirKomov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@PathVariable long userId, @RequestBody UserDto userDto) {
Готово, добавил группы валидации

2022-12-30 20:56 UTC, VladimirKomov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        log.info("Create {}", userDto.toString());
готово

2022-12-30 21:30 UTC, VladimirKomov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDtoResponse getItemById(@PathVariable long itemId) {
добавил валидацию в контроллер

2023-01-01 14:53 UTC, EvgenyKoptubenko approved these changes
Отличная работа. Спасибо огромное! Поздравляю с Новым Годом. Желаю в этом году пройти самый challenging roadmap, который только ты себе поставишь

2023-01-09 08:19 UTC, merged