sprint 15 - Add bookings
VladimirKomov/java-shareit pull request #2
Opened 2023-01-22 18:31 UTC by VladimirKomov

2023-01-22 19:55 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
Если добавить пользователя второй раз, то приходит некрасивое сообщение об ошибке 500.
{
	"code": "500 INTERNAL_SERVER_ERROR",
	"error": "could not execute statement; SQL [n/a]; constraint [\"PUBLIC.UK_6DOTKOTT2KJSP8VW4D0M25FB7_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ U&'email23222\\\\044b2@email.com' )\"; SQL statement:\ninsert into users (id, email, name) values (default, ?, ?) [23505-212]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}
 Хотя должно быть 409 Conflict или какое другое. По сути данные присланы неверные, а это не ошибка на стороне сервера

2023-01-22 20:01 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                LocalDateTime now = LocalDateTime.now();
лишняя переменная

2023-01-22 20:05 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse badRequest(final BadRequestException e) {
Я уж думал не найду ни одного замечания/предложения.
Эти обработчики эксепшенов можно объединить https://www.baeldung.com/exception-handling-for-rest-with-spring

2023-01-22 20:06 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Есть только предложение как улучшить обработку эксепшенов, ну и сообщение клиент получает 500, когда должно быть 409

2023-01-23 05:42 UTC, VladimirKomov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                LocalDateTime now = LocalDateTime.now();
готово

2023-01-23 06:22 UTC, VladimirKomov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse badRequest(final BadRequestException e) {
готово

2023-01-23 06:27 UTC, VladimirKomov commented on src/main/java/ru/practicum/shareit/user/UserController.java
готово

2023-01-23 06:28 UTC, VladimirKomov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse badRequest(final BadRequestException e) {
Рад, что нормально получилось, мне это не просто далось.

2023-01-23 06:36 UTC, VladimirKomov commented
С прошедшими праздниками, успехов во всем.

2023-01-23 19:26 UTC, EvgenyKoptubenko commented
> С прошедшими праздниками, успехов во всем.

Спасибо и тебя с праздниками!

2023-01-23 19:26 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо.

2023-01-24 05:42 UTC, merged