Add item requests
VladimirKomov/java-shareit pull request #3
Opened 2023-02-02 12:10 UTC by VladimirKomov

2023-02-03 18:35 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        String json = "{\"itemId\": 2,\"start\": \"" + localDateTime + "\",\"end\": \"" + localDateTime.plusDays(1) + "\"}";
попробуй все json'ы вынести в отдельные файлы. Таким образом будет проще видеть данные, которые отправляются, ожидаются в ответе. В принципе дата и время не столь важны в тестах. И с зафиксированными параметрами можно гарантировать то, что приложение работает так же и регрессия проходит

2023-02-03 18:44 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Замечаний нет.
Есть предложение тестовые данные вынести в отдельные файлы, чтобы не создавать json'ы на лету

2023-02-04 14:30 UTC, VladimirKomov commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        String json = "{\"itemId\": 2,\"start\": \"" + localDateTime + "\",\"end\": \"" + localDateTime.plusDays(1) + "\"}";
Готово

2023-02-04 17:44 UTC, VladimirKomov commented
Сможешь помочь, я немного запутался в dto, на одном вебинаре сказали что желательно чтобы сервис получал dto и отдавал dto, на другом, что лучше делать так чтобы контролер получал emtity и мапил в dto и отдавал. Я понимаю что это зависит от проекта и какой способ там используется так и нужно делать. Но допустим новый проект, какой подход предпочтительнее будет?

2023-02-04 19:23 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-02-06 09:08 UTC, merged