Add docker
VladimirKomov/java-shareit pull request #4
Opened 2023-02-11 07:40 UTC by VladimirKomov

2023-02-11 17:49 UTC, EvgenyKoptubenko commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> updateUser(@PathVariable @Min(0) Long userId,
Если отправить такой запрос curl --request PATCH \
  --url http://localhost:8080/users/1 \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"email":"wrong_emailmail.com",
  "login":"login22",
	"birthday":"2012-04-23T18:25:43.511Z"
}'
То приходит 500

{
	"code": "500 INTERNAL_SERVER_ERROR",
	"error": "Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction"
}

Должен быть Bad Request

2023-02-11 17:50 UTC, EvgenyKoptubenko commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Object> addBooking(
Если отправить такой запрос curl --request POST \
  --url http://localhost:8080/bookings \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 3' \
  --data '{
	"id":"11",
	"start":"2023-02-23T18:25:43.511Z",
	"end":"2032-04-23T18:25:43.511Z",
	"bookerId":"3",
	"itemId":"2"
	
}'
Но при этом нет пользователя, то клиенту приходит 404
{
	"code": "404 NOT_FOUND",
	"error": null
}
Нужно добавить более детальное описание ошибки

2023-02-11 17:51 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Замечаний по докеру нет. Есть предложение немного улучшить работу с эксепшенами, если есть желание.

2023-02-11 18:13 UTC, VladimirKomov commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> updateUser(@PathVariable @Min(0) Long userId,
готово, сам не понял зачем я @NotNull добавил, раньше @valid было. Проверил во всех.

2023-02-11 19:53 UTC, VladimirKomov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Object> addBooking(
готово, добавлено сообщение в NotfoundException

2023-02-12 16:40 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-02-12 16:56 UTC, merged